# Generated by Django 3.2 on 2022-01-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_auto_20220104_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Принадлежит к организации')),
            ],
            options={
                'verbose_name': 'Механика',
                'verbose_name_plural': 'Механики',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название параметра')),
                ('default_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Значение по-умолчанию')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.flow', verbose_name='Принадлежность к механике')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='ParameterChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_operator', models.CharField(choices=[('+', '[+] Сложение'), ('-', '[-] Вычиатение'), ('*', '[*] Умножение'), ('/', '[/] Деление')], max_length=1, verbose_name='Математический оператор')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Дельта (изменяемое значение)')),
                ('month_of_application', models.PositiveIntegerField(verbose_name='На какой месяц применять')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.card', verbose_name='Принадлежность к карточке')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.parameter', verbose_name='Изменяемый параметр')),
            ],
            options={
                'verbose_name': 'Изменение параметра',
                'verbose_name_plural': 'Изменения параметров',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.flow', verbose_name='Принадлежность к механике'),
        ),
    ]
