# Generated by Django 3.2 on 2022-01-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название механики'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='default_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начальное значение'),
        ),
        migrations.AlterField(
            model_name='parameterchange',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дельта (изменяемое значение)'),
        ),
    ]
