# Generated by Django 3.2 on 2022-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_auto_20220106_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.PositiveIntegerField(default=100000, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
