# Generated by Django 3.2 on 2022-01-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0003_card_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameter',
            new_name='Channel',
        ),
        migrations.RemoveField(
            model_name='parameterchange',
            name='parameter',
        ),
        migrations.AddField(
            model_name='parameterchange',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flows.channel', verbose_name='Изменяемый канал'),
            preserve_default=False,
        ),
    ]
