# Generated by Django 3.2 on 2022-01-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0004_auto_20220108_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('conversion', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Начальное значение')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.flow', verbose_name='Принадлежность к механике')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
    ]
