# Generated by Django 3.2 on 2022-01-08 19:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0005_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterchange',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flows.stage', verbose_name='Изменяемый этап'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='conversion',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.01)], verbose_name='Начальная конверсия'),
        ),
    ]
