# Generated by Django 3.2 on 2022-01-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0006_auto_20220108_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterchange',
            name='type',
            field=models.CharField(choices=[('FSVL', 'Изменение начального значения'), ('AVCH', 'Изменение среднего чека'), ('CONV', 'Изменение конверсии')], default=1, max_length=4, verbose_name='Тип изменений'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StageInSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(verbose_name='Место')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flows.stage', verbose_name='Изменяемый этап')),
            ],
            options={
                'verbose_name': 'Место в последовательности этапов',
                'verbose_name_plural': 'Места в последовательности этапов',
            },
        ),
    ]
