# Generated by Django 3.2 on 2022-03-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0008_alter_parameterchange_math_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Параметр / Канал', 'verbose_name_plural': 'Параметры / Каналы'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Этап воронки', 'verbose_name_plural': 'Этапы воронки'},
        ),
    ]
