# Generated by Django 3.2 on 2022-05-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0009_auto_20220322_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterchange',
            name='type',
            field=models.CharField(choices=[('FSVL', 'Изменение начального значения'), ('CONV', 'Изменение конверсии')], max_length=4, verbose_name='Тип изменений'),
        ),
    ]
