# Generated by Django 3.2.12 on 2022-12-19 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0010_alter_parameterchange_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='conversion',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.01)], verbose_name='Стандартная конверсия канала'),
        ),
        migrations.CreateModel(
            name='StageOfChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.01)], verbose_name='Конверсия канала')),
                ('channels', models.ManyToManyField(blank=True, max_length=255, to='flows.Channel', verbose_name='Принадлежность конверсии к каналам')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.stage', verbose_name='Принадлежность к стадии')),
            ],
            options={
                'verbose_name': 'Конварсия определенного канала на этапе',
                'verbose_name_plural': 'Конварсии определенного канала на этапе',
            },
        ),
    ]
