# Generated by Django 3.2.12 on 2022-12-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0012_alter_stage_conversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stageofchannel',
            options={'verbose_name': 'Конверсия определенного канала', 'verbose_name_plural': 'Конверсии определенного канала'},
        ),
    ]
