# Generated by Django 3.2.12 on 2022-12-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0013_alter_stageofchannel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stageofchannel',
            options={'verbose_name': 'Конверсия определенного канала', 'verbose_name_plural': 'Конверсии определенных каналов'},
        ),
    ]
