# Generated by Django 3.2.12 on 2023-02-13 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0016_alter_stage_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageofchannel',
            name='conversion',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0001)], verbose_name='Конверсия канала'),
        ),
    ]
