# Generated by Django 3.2 on 2022-01-04 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_auto_20220104_0930'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_turns', models.IntegerField(verbose_name='Количество шагов')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_month', to='rooms.month', verbose_name='Текущий месяц')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_room', to='rooms.room', verbose_name='В комнате')),
            ],
            options={
                'verbose_name': 'Раунд',
                'verbose_name_plural': 'Раунды',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, choices=[('1', 'I место'), ('2', 'II место'), ('3', 'III место')], max_length=1, null=True, verbose_name='Место')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.round', verbose_name='Раунд')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Призёр',
                'verbose_name_plural': 'Призёры',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.month', verbose_name='Месяц')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ход',
                'verbose_name_plural': 'Ходы',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='current_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_round', to='rooms.round', verbose_name='Текущий раунд'),
        ),
        migrations.AddField(
            model_name='room',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='В организации'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель комнаты'),
        ),
        migrations.AddField(
            model_name='month',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.round', verbose_name='Раунд'),
        ),
    ]
