# Generated by Django 3.2 on 2022-01-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_current_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='counter',
            field=models.IntegerField(default=1, verbose_name='Номер месяца'),
        ),
        migrations.AlterField(
            model_name='round',
            name='current_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_month', to='rooms.month', verbose_name='Текущий месяц'),
        ),
    ]
