# Generated by Django 3.2 on 2022-01-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20220104_0930'),
        ('rooms', '0003_auto_20220104_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='key',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('key', 'organization')},
        ),
    ]
