# Generated by Django 3.2 on 2022-01-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220104_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='key',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер комнаты в организации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='key',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер комнаты в организации'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('key', 'room')},
        ),
    ]
