# Generated by Django 3.2 on 2022-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220104_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='key',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер месяца в раунде'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='key',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер раунда в комнате'),
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together={('key', 'round')},
        ),
    ]
