# Generated by Django 3.2 on 2022-01-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20220104_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='place',
            field=models.CharField(choices=[('1', 'I место'), ('2', 'II место'), ('3', 'III место')], default=1, max_length=1, verbose_name='Место'),
            preserve_default=False,
        ),
    ]
