# Generated by Django 3.2 on 2022-01-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
        ('rooms', '0007_alter_winner_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.card', verbose_name='Карточка')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.turn', verbose_name='Ход')),
            ],
            options={
                'verbose_name': 'Выбор карточки',
                'verbose_name_plural': 'Выборы карточек',
            },
        ),
    ]
