# Generated by Django 3.2 on 2022-01-06 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_round_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан в'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён в'),
        ),
    ]
