# Generated by Django 3.2 on 2022-03-16 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0008_alter_parameterchange_math_operator'),
        ('rooms', '0013_auto_20220108_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='flows.flow', verbose_name='Механика комнаты'),
        ),
    ]
