# Generated by Django 3.2 on 2022-03-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0008_alter_parameterchange_math_operator'),
        ('rooms', '0014_room_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='flow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='flows.flow', verbose_name='Механика комнаты'),
            preserve_default=False,
        ),
    ]
