# Generated by Django 3.2.12 on 2022-12-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_auto_20221211_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
