# Generated by Django 3.2.12 on 2022-12-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_queue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Участник в очереди', 'verbose_name_plural': 'Участники в очереди'},
        ),
        migrations.RemoveField(
            model_name='queue',
            name='user',
        ),
        migrations.AddField(
            model_name='queue',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.roomparticipant', verbose_name='Участник'),
        ),
    ]
