# Generated by Django 3.2.12 on 2022-12-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_auto_20221225_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='participant',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.roomparticipant', verbose_name='Участник'),
        ),
    ]
