# Generated by Django 3.2.12 on 2022-12-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_auto_20221226_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Закончился ли'),
        ),
        migrations.AlterField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='В процессе ли'),
        ),
    ]
