# Generated by Django 3.2 on 2022-03-23 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0009_auto_20220322_2106'),
        ('rooms', '0015_alter_room_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageComputed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.01)], verbose_name='Конверсия')),
                ('cardinal_value', models.PositiveIntegerField(verbose_name='Входной трафик')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.stage', verbose_name="Изначальный 'этап воронки'")),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.turn', verbose_name='Шаг пользователя')),
            ],
            options={
                'verbose_name': 'Просчитанный этап',
                'verbose_name_plural': 'Просчитанный этапы',
            },
        ),
        migrations.CreateModel(
            name='ChannelComputed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardinal_value', models.PositiveIntegerField(verbose_name='Входной трафик')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.channel', verbose_name='Изначальный канал')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.turn', verbose_name='Шаг пользователя')),
            ],
            options={
                'verbose_name': 'Просчитанный канал',
                'verbose_name_plural': 'Просчитанный каналы',
            },
        ),
    ]
