# Generated by Django 3.2 on 2022-03-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelcomputed',
            options={'verbose_name': 'Просчитанный канал',
                     'verbose_name_plural': 'Просчитанные каналы'},
        ),
        migrations.AlterModelOptions(
            name='stagecomputed',
            options={'verbose_name': 'Просчитанный этап',
                     'verbose_name_plural': 'Просчитанные этапы'},
        ),
    ]
