# Generated by Django 3.2 on 2022-05-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computed', '0002_auto_20220330_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagecomputed',
            name='cardinal_value',
        ),
    ]
