# Generated by Django 3.2 on 2022-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computed', '0003_remove_stagecomputed_cardinal_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelcomputed',
            name='cardinal_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Входной трафик'),
        ),
    ]
