# Generated by Django 3.2.12 on 2022-12-29 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0014_alter_stageofchannel_options'),
        ('rooms', '0026_remove_round_is_old'),
        ('computed', '0004_alter_channelcomputed_cardinal_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageOfChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.01)], verbose_name='Конверсия канала')),
                ('stage_of_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.stageofchannel', verbose_name='Принадлежность к стадии')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.turn', verbose_name='Шаг пользователя')),
            ],
            options={
                'verbose_name': 'Конверсия определенного канала',
                'verbose_name_plural': 'Конверсии определенных каналов',
            },
        ),
    ]
