# Generated by Django 3.2.12 on 2022-12-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_remove_round_is_old'),
        ('flows', '0014_alter_stageofchannel_options'),
        ('computed', '0005_stageofchannel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StageOfChannel',
            new_name='StageOfChannelComputed',
        ),
    ]
