# Generated by Django 3.2.12 on 2023-03-29 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220104_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 28, 13, 44, 9, 90269, tzinfo=utc), verbose_name='Дата окончания подписки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор организации'),
        ),
    ]
