# Generated by Django 3.2 on 2022-01-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20220104_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_turns_default', models.PositiveIntegerField(verbose_name='Количество шагов в комнате по умолчанию')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Настройки организации',
                'verbose_name_plural': 'Настройки организаций',
            },
        ),
    ]
