# Generated by Django 3.2 on 2022-01-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', unique=True, verbose_name='Организация'),
        ),
    ]
