# Generated by Django 3.2 on 2022-01-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationsettings_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация'),
        ),
    ]
