# Generated by Django 3.2 on 2022-01-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationsettings_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='number_of_turns_default',
            field=models.PositiveIntegerField(default=3, verbose_name='Количество шагов в комнате по умолчанию'),
        ),
    ]
