# Generated by Django 3.2 on 2022-03-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizationsettings_number_of_turns_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_owner_id',
            new_name='organization_owner',
        ),
    ]
