# Generated by Django 3.2 on 2022-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_rename_organization_owner_id_organization_organization_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(max_length=50, unique=True, verbose_name='Поддомен'),
        ),
    ]
