# Generated by Django 3.2 on 2022-03-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organization_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(max_length=50, verbose_name='Поддомен'),
        ),
    ]
